### ISSUE TITLE
How to specify the main html file or customRun in the project settings

### ISSUE THREAD

**Issue by gagranov** [jbaron/qx-typed#9]
Hi,

I am trying to run the qx-typed application and did everything as it was prescribed (or at least that what I think),

but I am getting this error:

"Please specify the main html file or customRun in the project settings"

and do not know how to fix it :(

Please advise,

Thanks,
Gennady

**Comment by tcsaddul** [comment]
Sorry for late reply.

This is how I structured my Main module:

module main {
    export class TApp {

        constructor() {
            qx.registry.registerMainMethod(TApp.mainFunc);
        }

        static mainFunc(app: qx.application.Standalone): void {
	    // Your startup code here
        }
    }

    let mainApp = new TApp();
}

And here is my main html file:

<!DOCTYPE html>
<html>
<head>
    <title>Title of Application</title>
    <script type="text/javascript">
        function loadScript(url, callback) {
            var s = document.createElement("script");
            s.charset = "utf-8";
            s.type = "text/javascript";
            s.async = true;
            s.src = url;
            s.onreadystatechange = s.onload = function() {                
	       if (typeof callback === "function") {                    
	           callback();                
	       }
            };
 
	    document.getElementsByTagName("head")[0].appendChild(s);
        }

        var r = new XMLHttpRequest();
        r.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var v = JSON.parse(this.responseText);
                loadScript(window.location.protocol + "//" + window.location.host + "/scripts/qooxdoo5.0.2b.min.js", function() {
	            loadScript("scripts/app.min.js?version=" + v);
		});
            }
        };
        r.open("GET", "version", true);
        r.send();
    </script>
</head>
<body>
</body>
</html>

This technique will reload only our main application (app.min.js) when the server replies a newer or different version.

**Comment by hlizard** [comment]
Maybe just forget build(Project - Build Project) before run like me.
